name: AbyssRl pipeline
run-name: ${{github.actor}} triggered tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: install dependencies
        run: npm install
      - name: build
        run: npm run build:prod
  type-check:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: install dependencies
        run: npm install
      - name: type-check
        run: npm run typecheck
  unit-tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: install dependencies
        run: npm install
      - name: unit tests
        run: npm test
  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: install dependencies
        run: npm install
      - name: eslint
        run: npm run lint:ts
  e2e-tests:
    runs-on: ubuntu-latest
    needs: [type-check]
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: e2e tests
        uses: cypress-io/github-action@v4.0.0
        with: 
          build: npm run build:prod
          start: npm run start:server:prod
          browser: edge

      