name: AbyssRl pipeline
run-name: ${{github.actor}} triggered tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build:prod
      - name: Start server
        run: npm run start:server:prod
      - name: e2e tests
        run: npm run cypress:edge
      